name: CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Run Tests for Backend
  test-backend:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Verify MongoDB URI
        env:
          MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
        run: |
          if [ -z "$MONGODB_URI_TEST" ]; then
            echo "MONGODB_URI_TEST is not set."
            exit 1
          fi
          echo "MONGODB_URI_TEST is set."
      
      - name: Install dependencies
        working-directory: backend
        run: npm install
      
      - name: Run Tests
        working-directory: backend
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
        run: npm test

   # Step 2: Deploy Backend
  deploy-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy Backend
        working-directory: backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service backend-service
  
  # Step 3: Build and Deploy Frontend
  build-and-deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install
      
      - name: Debug VITE_API_URL
        working-directory: frontend
        env:
          VITE_API_URL: ${{ env.API_URL }}
        run: |
          if [ -z "$VITE_API_URL" ]; then
            echo "VITE_API_URL is not set."
            exit 1
          else
            echo "VITE_API_URL is set to: $VITE_API_URL"
          fi

      - name: Build Frontend with API URL
        working-directory: frontend
        env:
          VITE_API_URL: ${{ env.API_URL }}
        run: npm run build

      - name: Deploy Frontend
        working-directory: frontend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service frontend-service
